### ISSUE TITLE
OneToOneRelations can only be used if they are in the same namespace

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#216]
As of cd9b3561a088b84f4fadc6e678cc24cbf58f45a5 the following datamodel definition does not compile
```yaml
datatypes:
  example::NamespacedType:
    # necessary definition

  DataTypeWithRelation:
    # necessary definition
    OneToOneRelation:
      - example::NamespacedType relation // a relation in a different namespace
```

The corresponding compiler error:
```console
../tests/src/DataTypeWithRelationCollectionData.cc: In member function ‘void DataTypeWithRelationCollectionData::setReferences(const podio::ICollectionProvider*, bool)’:
../tests/src/DataTypeWithRelationCollectionData.cc:107:36: error: expected type-specifier before ‘ConstNamespacedType’
  107 |       entries[i]->m_relation = new ConstNamespacedType((*tmp_coll)[id.index]);
      |                                    ^~~~~~~~~~~~~~~~~~~
../tests/src/DataTypeWithRelationCollectionData.cc:106:42: warning: unused variable ‘tmp_coll’ [-Wunused-variable]
  106 |       example::NamespacedTypeCollection* tmp_coll = static_cast<example::NamespacedTypeCollection*>(coll);
      |                                          ^~~~~~~~

```
