### ISSUE TITLE
spack installation of podio fails

### ISSUE THREAD

**Issue by deepaksamuel** [AIDASoft/podio#222]
- OS version: Ubuntu 21.04
 - Compiler version: GCC 10.3.0
 - PODIO version: 00-13-01
 - Reproduced by: running spack install with the following specs
 - Input: spack file:
```
 spack:
  specs:
  - acts +dd4hep +digitization +examples +fatras +identification +json +tgeo +ipo
  - cmake
  - clhep cxxstd=17
  - dd4hep +geant4 +assimp +hepmc3 +lcio +ipo
  - eigen
  - gaudi@36.0 +ipo
  - geant4 +ipo +qt +opengl -python +vecgeom cxxstd=17
  - genfit +ipo
  - hepmc3 +interfaces +python +rootio
  - lcio +ipo
  - mesa -llvm swr=none
  - opencascade +ipo +tbb -vtk
  - podio +ipo
  - pythia8 +fastjet
  - root cxxstd=17 +fftw +fortran +gdml +mlp +pythia8 +root7 +tmva +vc +xrootd +ssl
  - xrootd cxxstd=17 +python
  concretization: together
  config:
    install_missing_compilers: true
    install_tree:
      root: /opt/software
  view: /opt/local
```
 - Output: 1 error found in build log:
```
     68    
     69    
     70         'Homage to the Square' - Josef Albers
     71    
     72    -- Not adding the SIO Blocks library to the targets because the corresponding c++ sources have not been generated
     73    -- Configuring done
  >> 74    CMake Error at src/CMakeLists.txt:20 (add_library):
     75      No SOURCES given to target: podio
     76    
     77    
     78    CMake Generate step failed.  Build files cannot be regenerated correctly.
```

 - Goal: Trying to install EIC related software
