### ISSUE TITLE
Allow for relations between two arbitrary types

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#255]
Currently to relate two collections or objects of two collections a dedicated type is necessary. This datatype usually has a `float weight` as single datamember and then two `OneToOneRelation`s to connect two objects.

E.g. from [EDM4hep](https://github.com/key4hep/EDM4hep/blob/b1b0b2bb68009c253079f652423ede4b4dec6b5e/edm4hep.yaml#L413-L420)
```yaml
  edm4hep::MCRecoParticleAssociation:
    Description: "Used to keep track of the correspondence between MC and reconstructed particles"
    Author: "C. Bernet, B. Hegner"
    Members:
      - float weight                        // weight of this association
    OneToOneRelations :
     - edm4hep::ReconstructedParticle  rec  // reference to the reconstructed particle
     - edm4hep::MCParticle sim              // reference to the Monte-Carlo particle
```

LCIO allows for arbitrary relations between two objects, via the [`LCRelation`](https://ilcsoft.desy.de/LCIO/current/doc/doxygen_api/html/classEVENT_1_1LCRelation.html). In order to handle all of the relations that are used in the wild many new `Association` types have to be introduced to EDM4hep, e.g.
- key4hep/EDM4hep#122
- key4hep/EDM4hep#133

It might be simpler to implement a generic (templated) association or relation type in podio that then allows to use (and persist) arbitrary relations between objects.
