### ISSUE TITLE
Allow setting default initializers on member definition

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/podio#266]
Data type components are currently defined as, e.g.,
```yaml
    # Vector3D with floats
    edm4hep::Vector3f :
      Members:
        - float x
        - float y
        - float z
      ExtraCode:
        declaration: "
        Vector3f() : x(0),y(0),z(0) {}\n
        Vector3f(float xx, float yy, float zz) : x(xx),y(yy),z(zz) {}\n
        "
```

A common pattern is to set the default initialization of a type (e.g. `Vector3f() : x(0),y(0),z(0) {}`) which requires a constructors. Since C++11 we can use default initializer lists for non-static members, https://en.cppreference.com/w/cpp/language/data_members. This would allow (suggest?) a syntax in yaml:
```yaml
    # Vector3D with floats
    edm4hep::Vector3f :
      Members:
        - float x{0}
        - float y{0}
        - float z{0}
      ExtraCode:
        declaration: "
        Vector3f(float xx, float yy, float zz) : x(xx),y(yy),z(zz) {}\n
        "
```
In this example, chosen for its simplicitly, this would only get rid of a single default constructor. Other examples would be differently affected (e.g. a 4d covariance matrix with a default, diagonal, and full constructors).

**Comment by tmadlener** [comment]
This looks like a very reasonable addition. Plus we will most likely need something like this for schema evolution in any case.

For clarification (and also because I couldn't find this in the documentation quickly): The data members of components and datatypes are default initialized in any case, so the `Vector3f` definition above will be generated to
```cpp
namespace edm4hep {
struct Vector3f {
  float x{};
  float y{};
  float z{};
  // ExtraCode ...
};
}
```

Adding the possibility to have user defined default values in the yaml file, should not be too complicated. From a syntax point of view, I think `{<value>}` is as good as ` = <value> `.

I suppose we would want an optional default (value) initialization in the yaml file, or would we mandate that users provide default values for all members?

**Comment by wdconinc** [comment]
I think, in the interest of backwards compatibility, keeping it optional would be my preference.

**Comment by tmadlener** [comment]
Just to better define the overall scope:
- Should the default initialization with user provided values also work for arrays? If we do, how far should we go in validation already on the python side?
- How far should we try and validate "reasonable" default values already on the python side? e.g. should we check that `int`s are actually initialized by an integer value and not for example a `float` value.

The reason I am asking: Getting user defined default values for the "happy case" is not too much work. However, trying to catch all potential user errors here might require an actual parser instead of the regex based thing we have at the moment. Up until now we have at least tried to be on the rather strict side with our validation, so that we can avoid users running into compiler errors in generated code.

**Comment by wdconinc** [comment]
Those are all good questions :-)

Validation of the provided values seems like a sensible goal, even if it may never be able to accurately validate things like this:
```yaml
  edm4hep::TrackerHit:
    Description : "Tracker hit"
    Author : "F.Gaede, DESY"
    Members :
      - edm4hep::Vector3d position{0,0,0}
      - std::array<float,6> covMatrix{1,1,1,0,0,0}
```
especially for custom-defined components. These are not simple local validation decisions anymore and a regex parser will not be able to catch them.

When is the validation typically applied?
1. user writes yaml with data model
2. user generates classes from data model
3. user compiles classes and installs headers and libraries
4. user compiles code against installed headers and libraries

The python-side validation is now in step 2, I take it. How often is there is a separation between steps 2 and 3? Step 3 inherently involves a validation through compilation (based on the syntactic analysis that is required for it)? Could the syntactic analysis that is done in step 3 be included at the end of step 2 (and would that actually make sense if step 3 is always next anyway)?
