### ISSUE TITLE
Components with `std::array` members cannot be used in datatypes if `exposePODMembers` is true

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/podio#269]
The generated `ostream operator<<` overload of the datatypes does not compile as it currently requires an overload for `std::array`, which is not there.

E.g. the following minimal example
```yaml
--- 
options:
  exposePODMembers: True
  getSyntax: False

components:
  Comp:
    Members:
      - std::array<int, 3> arr

datatypes:
  Type:
    Author: "XYZ"
    Description: "Showcase"
    Members:
      - Comp comp // component with array that breaks compilation
```

would break, because the generated `ostream operator<<` overload would look like
```cpp
std::ostream& operator<<(std::ostream& o, const Type& value) {
  o << " id: " << value.id() << '\n';
  o << " comp : " << value.comp() << '\n';
  o << " comp: " << value.arr() << '\n';

  return o;
}
```
which tries to output a `std::array` via `value.arr()`.

Additionally, this prints information twice, because printing the component already prints the contents of the component.

Note that this starts to work again if a component has another component with an array, e.g. what we have in our tests:
https://github.com/AIDASoft/podio/blob/d00f8cf8c76d5e405bb8bc7afae3ffa8a82b8dfd/tests/datalayout.yaml#L11-L16
https://github.com/AIDASoft/podio/blob/d00f8cf8c76d5e405bb8bc7afae3ffa8a82b8dfd/tests/datalayout.yaml#L24-L26
https://github.com/AIDASoft/podio/blob/d00f8cf8c76d5e405bb8bc7afae3ffa8a82b8dfd/tests/datalayout.yaml#L104-L108
