### ISSUE TITLE
Enhancement/question: subset collections with relations

### ISSUE THREAD

**Issue by wdconinc** [AIDASoft/podio#320]
It often makes sense to store a collection of objects that is simply a subset of a larger collection. E.g. for a collection of `ReconstructedParticles` it may make sense to store a subset collection `ReconstructedMuons` which does not need a copy of the original `ReconstructedParticle` entries, but simply a relation to them. This would essentially be what can be achieved as a data type such as (for `MCParticle`):
```yaml
  emd4hep::MCParticleRef:
    Description: "MCParticle reference"
    OneToOneRelations:
      - edm4hep::MCParticle ref
```
Would it make sense to build this in at the podio template level so this functionality is automatically provided for all types, or at the yaml parsing level, or is there a more efficient to approach to this without a data model extension on the user end?
