### ISSUE TITLE
OneToOne relations are not preserved on `clone()` since v01-00

### ISSUE THREAD

**Issue by veprbl** [AIDASoft/podio#631]
!!!IMPORTANT!!!: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information

 - OS version: e.g. SLC6
 - Compiler version: e.g GCC 6.2
 - PODIO version: 01-00
 - Reproduced by: 

sorry, no exact steps, but the idea is we start with:
```yaml
  edm4eic::MCRecoTrackParticleAssociation:
    Description: "Association between a Track and a MCParticle"
    Author : "S. Joosten"
    OneToOneRelations:
      - edm4hep::MCParticle sim             // reference to the Monte-Carlo particle
```
then we fill that with both `rec` and `sim` set.
```c++
MCRecoTrackParticleAssociationCollection *partassocs_in;
for (auto assoc_in : *partassocs_in) {
  // assoc_in.getSim().isAvailable() == 1
  auto assoc_out = assoc_in.clone();
  // assoc_out.getSim().isAvailable() == 0 <- BUG
}
```

 - Input: link to input files if applicable
 - Output: full build and run log output
 - Goal: running existing eicrecon code

Bisect shows that 02a4b9d5d704eb572ce945594b4c85303e89e216 is the first bad commit
